### ISSUE TITLE
Inference fails with --path-images and multiple images

### ISSUE THREAD

**Issue by hermancollin** [ivadomed/utilities#33]
https://github.com/ivadomed/utilities/blob/05650ed97782ab650774aa81b8a76aa2646e37e2/packaging/run_nnunet_inference.py#L143-L146

Inference currently fails when specifying a list of individual images using the `--path-images` arg. Everything is saved in the same file. Only way to specify a list of images is to specify them one at a time.

**Comment by naga-karthik** [comment]
Thanks for opening the issue! 

> Only way to specify a list of images is to specify them one at a time.

So, you mean like running inference X times for X images? Also, if you have a list of images, have you tried putting them in a folder instead and then using `path_dataset`?

Trying the script on list of images might have been one case I did not test, hence the error.

**Comment by hermancollin** [comment]
> So, you mean like running inference X times for X images? Also, if you have a list of images, have you tried putting them in a folder instead and then using `path_dataset`?
> 

Yes that's what I meant. When I put the images in a folder and use `--path_dataset`, the script outputs that there is 0 cases in the source folder. If someone can reproduce the issue first, I could try to fix these small bugs.

**Comment by hermancollin** [comment]
This is fixed now after changes in inference method and fixes from #39
