### ISSUE TITLE
Inference script: postprocess range from [0,1] to [0,255]

### ISSUE THREAD

**Issue by hermancollin** [ivadomed/utilities#37]
Minor suggestion: I don't know if this is something that bothers anyone else, but nnUNet saves predictions with 0 and 1 values. It's not practical because the mask is encoded in 8bit precision, so it cannot be conveniently read. A simple fix is to multiply everything by 255. Since this is an inference script, this option could be provided with an optional arg.

**Comment by naga-karthik** [comment]
I personally have never found this to be an issue, hence the range was fine for me. Maybe adding an argument as you suggeseted would be good in case users want that!

**Comment by hermancollin** [comment]
@naga-karthik ah that makes sense. I guess you never view annotations or masks in traditional image viewers (gimp, photoshop etc) so this problem never came up.

In that case I don't think it's worth adding it to the common inference script.
