### ISSUE TITLE
nnUNetPredictor available in newest nnUNetv2 pip package

### ISSUE THREAD

**Issue by hermancollin** [ivadomed/utilities#38]
https://github.com/ivadomed/utilities/blob/de4f1f7162a3dec89292f861856a1d50cd432a20/packaging/run_nnunet_inference.py#L151-L154

Just want to point out that option 2 is now usable with the newest nnUNetv2 pip package (v2.2, released 3 weeks ago)

**Comment by valosekj** [comment]
Nice! Thanks for letting us know!

TODO:
- [ ] update the script

**Comment by naga-karthik** [comment]
Thanks @hermancollin for opening the issue! I updated the inference code to follow the latest nnunet version

For `run_nnunet_inference.py` -- refer to commit f66d627f23e5f800803367847ee1c15acd51ed2c
For `run_inference_single_subject.py` -- refer to commit 7c46dd9d2cee144119b10a3fbdc234f5d4527321

@hermancollin can you please try testing one of these inference scripts and let me know if it works? Thanks!

**Comment by hermancollin** [comment]
@naga-karthik sure I can test this. Only thing to look out for is that v2.2 requires python >= 3.9 (I know it caused some issues for Mathieu). Maybe this should be specified somewhere.

Also, @valosekj is there a specific reason why the requirements file is a .py file? I thought it was a typo so I renamed the file but if there is a reason for this we can always change it back. Nevertheless, we also need to bump the nnunetv2 version here:

https://github.com/ivadomed/utilities/blob/7c46dd9d2cee144119b10a3fbdc234f5d4527321/packaging/run_nnunet_inference_requirements.py#L29

I pushed a patch for this.

Apart from this, there were problems with the script and I was not able to segment images, both with `--path-dataset` and `--path-images`. I fixed some obvious typos in variable names but it still doesn't work on my side. I will take a closer look at this tomorrow.

**Comment by valosekj** [comment]
> Also, @valosekj is there a specific reason why the requirements file is a .py file? I thought it was a typo so I renamed the file but if there is a reason for this we can always change it back. Nevertheless, we also need to bump the nnunetv2 version here:

Good catch! You're right, it is a typo.

**Comment by hermancollin** [comment]
I fixed some minor stuff in #39. It's possible that run_inference_single_subject is not affected by this change because the user does not have the option to use a folder for segmentation.
