### ISSUE TITLE
Consider moving `compute_metrics/compute_metrics_reloaded.py` to `ivadomed/MetricsReloaded`

### ISSUE THREAD

**Issue by valosekj** [ivadomed/utilities#52]
Consider moving https://github.com/ivadomed/utilities/blob/main/compute_metrics/compute_metrics_reloaded.py to https://github.com/ivadomed/MetricsReloaded

**Comment by naga-karthik** [comment]
can this be prioritized please? I am using the script in two projects and I don't want to install utitilies separately in two different project envs.

**Comment by valosekj** [comment]
Done in https://github.com/ivadomed/MetricsReloaded/pull/5

TODO: remove the scripts from this repo
